/* PAI 2.0 — professions.js
 * Dados básicos de cada profissão. O conteúdo específico de cada capítulo
 * (tarefas, pedidos, anotações, números) fica dentro do próprio capítulo,
 * num objeto BY_PROF, para que todo capítulo suporte as 6 profissões.
 */
(function () {
  'use strict';
  const P2 = (window.P2 = window.P2 || {});

  P2.PROFS = {
    escritorio: {
      id: 'escritorio',
      jorge: { papel: 'colega de setor', desc: 'trabalha na mesa ao lado' },
      label: 'Escritório / Gestão',
      short: 'Escritório',
      icon: '💼',
      desc: 'Relatórios, e-mails, planilhas, reuniões e equipe.',
      oficio: 'gestor',
      cor: '#4a7bd1',
      local: 'escritório',
      noLocal: 'no escritório',
      doLocal: 'do escritório',
      chefe: { nome: 'Dona Marta', titulo: 'gerente', tipo: 'chefe', variant: 'tailleur', cor: '#5b5768', artigo: 'a', ele: 'ela' },
    },
    comercio: {
      id: 'comercio',
      jorge: { papel: 'dono da loja vizinha', desc: 'tem a lojinha de utilidades ao lado' },
      label: 'Comércio / Negócio próprio',
      short: 'Comércio',
      icon: '🏪',
      desc: 'Loja, clientes, estoque, preço, caixa e redes sociais.',
      oficio: 'dono de loja',
      cor: '#d1574a',
      local: 'loja',
      noLocal: 'na loja',
      doLocal: 'da loja',
      chefe: { nome: 'Dona Neide', titulo: 'cliente mais antiga da loja', tipo: 'cliente', variant: 'casual', cor: '#b0507a', artigo: 'a', ele: 'ela' },
    },
    saude: {
      id: 'saude',
      jorge: { papel: 'colega da clínica', desc: 'atende na sala ao lado' },
      label: 'Saúde',
      short: 'Saúde',
      icon: '🩺',
      desc: 'Clínica, pacientes, agenda, orientações e estudos.',
      oficio: 'profissional de saúde',
      cor: '#3aa88a',
      local: 'clínica',
      noLocal: 'na clínica',
      doLocal: 'da clínica',
      chefe: { nome: 'Dra. Helena', titulo: 'diretora clínica', tipo: 'chefe', variant: 'jaleco', cor: '#f4f1e8', artigo: 'a', ele: 'ela' },
    },
    engenharia: {
      id: 'engenharia',
      jorge: { papel: 'mestre de obras', desc: 'toca a obra com você há anos' },
      label: 'Engenharia / Obras',
      short: 'Engenharia',
      icon: '🏗️',
      desc: 'Obra, cronograma, orçamento, relatórios e normas.',
      oficio: 'engenheiro',
      cor: '#e0a030',
      local: 'obra',
      noLocal: 'na obra',
      doLocal: 'da obra',
      chefe: { nome: 'Seu Valdir', titulo: 'dono da obra', tipo: 'cliente', variant: 'capacete', cor: '#e0a030', artigo: 'o', ele: 'ele' },
    },
    direito: {
      id: 'direito',
      jorge: { papel: 'colega de escritório', desc: 'advoga na sala ao lado' },
      label: 'Direito',
      short: 'Direito',
      icon: '⚖️',
      desc: 'Contratos, prazos, petições, clientes e pesquisa.',
      oficio: 'advogado',
      cor: '#6a4aa0',
      local: 'escritório',
      noLocal: 'no escritório',
      doLocal: 'do escritório',
      chefe: { nome: 'Dr. Augusto', titulo: 'sócio do escritório', tipo: 'chefe', variant: 'terno', cor: '#3a3646', artigo: 'o', ele: 'ele' },
    },
    autonomo: {
      id: 'autonomo',
      jorge: { papel: 'parceiro de serviço', desc: 'divide a oficina e os bicos com você' },
      label: 'Autônomo / Prestador de serviço',
      short: 'Autônomo',
      icon: '🧰',
      desc: 'Orçamentos, clientes, agenda, WhatsApp e divulgação.',
      oficio: 'prestador de serviço',
      cor: '#2f8f5a',
      local: 'oficina',
      noLocal: 'na oficina',
      doLocal: 'da oficina',
      chefe: { nome: 'Dona Rose', titulo: 'cliente', tipo: 'cliente', variant: 'casual', cor: '#4166a8', artigo: 'a', ele: 'ela' },
    },
  };
  P2.PROF_ORDER = ['escritorio', 'comercio', 'saude', 'engenharia', 'direito', 'autonomo'];
})();
